spring.application.name=Backend
spring.mongodb.uri=mongodb+srv://lakshmidusanapudi10:greeting@greetings.0twxm7t.mongodb.net/Restaurants?appName=Greetings
jwt.secret=MyRestaurantBookingApplicationSecretKeyForJWTAuthentication123456789
jwt.expiration=86400000
cloudinary.cloud-name=dfelo5uvd
cloudinary.api-key=492169725964951
cloudinary.api-secret=RmNTaK24_Z3XRFLuh5z1e0VVR-0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=drajyalakshmi03@gmail.com
spring.mail.password=pquh qtly rkot mqws

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
